# Generated by Django 5.1.1 on 2024-09-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
    ]
