# Generated by Django 5.1.1 on 2024-09-23 02:20

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_dailytotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 23)),
        ),
    ]
