# Generated by Django 5.1.1 on 2024-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_dailytotal_date_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='Unnamed Meal', max_length=255),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='sugars',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytotal',
            name='total_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytotal',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytotal',
            name='total_fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytotal',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytotal',
            name='total_sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytotal',
            name='total_sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
