# Generated by Django 5.1.1 on 2024-09-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_meal_calories_meal_carbs_meal_fats_meal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='sugars',
        ),
    ]
