# Generated by Django 5.1.1 on 2024-09-25 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_meal_calories_remove_meal_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
