# Generated by Django 5.1.1 on 2024-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_mealitem_quantity_remove_mealitem_servingsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mealType',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Drink', 'Drink')], default='Snack', max_length=100, null=True),
        ),
    ]
